monarch-initiative/MAxO

.travis.yml
src/ontology/maxo-edit.owl

Fixed spaces in xrefs and added Nicole, Lauren, and Peter to travis notifications.

Fix errors and update .travis.yml

---

src/patterns/data/manual/avoidance_of_medical_action.tsv
src/patterns/data/manual/swab_by_location.tsv
src/patterns/dosdp-patterns/radiograph_by_location.yaml
src/patterns/dosdp-patterns/swab_by_location.yaml

@lccarmody hope they all make sense! Please check the diffs. Note that this pull request merges into covid19 branch - not master!

Some bugfixes

---

src/ontology/maxo-edit.owl

Last term to be added from #158.  All other terms have been either added to MAXO or have migrated to other issues.

added NIPPV to update #158 and #160

---

src/ontology/maxo-edit.owl
src/patterns/data/manual/transplantation_by_location.tsv

update synonym for corneal transplant

---

src/ontology/maxo-edit.owl

Issue 183-kidney procedures

---

src/ontology/maxo-edit.owl

changed parentage of pain management and added new term 'pain management for palliative care'

Pain management for palliative care

---

src/ontology/maxo-edit.owl

sleep apnea terms

---

src/ontology/maxo-edit.owl

alliedhealth and obstetric procedures

---

src/ontology/maxo-edit.owl

add synonym to audiometric testing

---

src/ontology/maxo-edit.owl
src/patterns/data/manual/protein_measurement_serum.tsv

add MAXO_0009012 intrauterine fetal transfusion. Close #284

add intrauterine fetal transfusion

---

maxo-base.json
maxo-base.obo
maxo-base.owl
patterns/definitions.owl
src/ontology/maxo-edit.owl
src/ontology/reports/maxo-edit.owl-obo-report.tsv
src/patterns/definitions.owl

fixed duplicate definitions and wrong annotation lables.

Fix defs errors

---

src/ontology/maxo-edit.owl

See https://bioregistry.io/registry/ncbibook for more information about this prefix

Standardize xrefs to NCBI Book

---

src/ontology/maxo-edit.owl
src/patterns/data/manual/radiograph_by_location.tsv

develop surgical repair branch

Issue 258 surgical repair

---

src/ontology/maxo-edit.owl

- cardiac surgery
- congenital heart defect repair
- vision treatment
- glasses usage
- nasolacrimal duct surgery
- strabismus surgery
close #319

add new terms for INCLUDE DCC

---

src/ontology/maxo-edit.owl
src/patterns/data/manual/pharmacotherapy_chemicalrole.tsv

Add Janus Kinase kinase inhibitor therapy and GABA transaminase inhibitor agent therapy

Add Pharmacotherapy terms

---

src/ontology/maxo-edit.owl

and add NCIT dbxref
close #337

add synonym to tumorectomy

---

src/ontology/maxo-edit.owl
src/patterns/definitions.owl

Delete assertion making inheres_in as subclass of radioactive.
Close #359

delete axiom inheres_in as subclass of radioactive

---

maxo-base.json
maxo-base.obo
maxo-base.owl
patterns/definitions.owl
patterns/pattern.owl
src/ontology/imports/chebi_terms_combined.txt
src/ontology/imports/foodon_import.owl
src/ontology/imports/go_import.owl
src/ontology/imports/hp_import.owl
src/ontology/imports/iao_import.owl
src/ontology/imports/obi_import.owl
src/ontology/imports/pr_import.owl
src/ontology/imports/pr_terms_combined.txt
src/ontology/imports/ro_import.owl
src/ontology/reports/maxo-edit.owl-obo-report.tsv
src/ontology/tmp/seed.txt
src/patterns/pattern.owl

This is to fix pharmacotherapy --circular logical definition which caused it to be root. There are other minor fixes to DOSDP pattern and small changes to hierarchy.

release for pharmacotherapy and minor fixes

---

src/ontology/maxo-edit.owl
src/patterns/definitions.owl
src/patterns/dosdp-patterns/avoidance_of_behavior_process.yaml
src/patterns/dosdp-patterns/avoidance_of_medical_action.yaml
src/patterns/dosdp-patterns/avoidance_of_phenotype.yaml
src/patterns/dosdp-patterns/biopsy_by_location.yaml
src/patterns/dosdp-patterns/endoscopy_by_location.yaml
src/patterns/dosdp-patterns/examination_by_location.yaml
src/patterns/dosdp-patterns/radiograph_by_location.yaml
src/patterns/dosdp-patterns/ultrasonography_by_location.yaml

Issue 263 Education support

---

src/ontology/maxo-edit.owl

Occupational therapy, etc.

---

src/ontology/maxo-edit.owl
src/patterns/data/manual/avoidance_of_food_intake.tsv
src/patterns/data/manual/removal_by_phenotype.tsv
src/patterns/definitions.owl

Fix typos and duplicate synonyms in #539 #610 #596

Orcids and typos

---

src/ontology/components/maxo-template.owl
src/ontology/maxo-edit.owl
src/patterns/definitions.owl
src/templates/replaced.tsv

Updating the hierarchy structure to make sure it makes sense/decrease redundancy

Diagnostic hierarchy updates

---

src/ontology/maxo-edit.owl

Added a route of administration branch including skin, topical, trans…dermal, enteral, intravenous, vaginal, rectal, ocular, eye drop, intravitreal, nasal, otic, parenteral, oral, buccal, sublingual to address #617 #324

Route of administration branch 

---

src/ontology/maxo-edit.owl

add hearing aid use with FM amplification

---

src/ontology/maxo-edit.owl

Issue 331 denture

---

src/ontology/maxo-edit.owl

added synonym to immunoglobulin infusion therapy #493

mmunoglobulin infusion therapy #493

---

src/ontology/maxo-edit.owl

removal of ovarian cyst

---

src/ontology/maxo-edit.owl

@matentzn 
Hi Nico, could you please sanity check this? I would like to start editing MAxO a little more frequently for the various other projects!

new diagnostics terms

---

src/ontology/maxo-edit.owl

@matentzn  I have merged one term (obsolete examination by a neurologist) the same was as in HPO. Could you please sanity check this? If it is OK, I will do the rest and we could make a new release. Thanks!

testing merging of obsolete examination by a neurologist
